In [ ]:
import os
import sys

sys.path.append(os.path.abspath(".."))

import pandas as pd
from src.config import DATA_PATH

df = pd.read_json("../" + DATA_PATH, lines=True)

df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-07-18 22:58:37.948,0,True
1,1,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2020-06-20 18:42:29.731,0,True
2,5,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2018-04-07 09:23:37.534,0,True
3,5,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,2010-11-20 18:41:35.000,18,True
4,5,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,2023-02-17 02:39:41.238,0,True

In [3]:
df.shape

(50000, 10)

In [4]:
df.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             50000 non-null  int64
 1   title              50000 non-null  str
 2   text               50000 non-null  str
 3   images             50000 non-null  object
 4   asin               50000 non-null  str
 5   parent_asin        50000 non-null  str
 6   user_id            50000 non-null  str
 7   timestamp          50000 non-null  datetime64[ms]
 8   helpful_vote       50000 non-null  int64
 9   verified_purchase  50000 non-null  bool
dtypes: bool(1), datetime64[ms](1), int64(2), object(1), str(5)
memory usage: 24.6+ MB

In [6]:
df.isna().sum()

rating               0
title                0
text                 0
images               0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
dtype: int64

In [7]:
df["rating"].value_counts().sort_index()

rating
1     4144
2     2117
3     3412
4     7383
5    32944
Name: count, dtype: int64

In [8]:
df[["rating", "title", "text"]].sample(5, random_state=42)

,rating,title,text
33553,5,Functional and easy to use,It clamps onto the desk and is easy to use. I...
9427,5,Great Product,Great Product
199,4,A good case for the price,A good case for the price. I was nervous that ...
12447,5,Webcam 2K HD Streaming Camera,"Small, but does the job"
39489,5,Great,Awesome